# Generated by Django 3.2.8 on 2022-03-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220228_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='Null', upload_to='uploads/categories/'),
        ),
    ]
